# Generated by Django 2.1.3 on 2018-11-03 15:31

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag_color',
            field=models.CharField(default=products.models.Product.random_color, max_length=7),
        ),
    ]
