# Generated by Django 2.1.2 on 2018-11-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181031_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('technician', 'tech')], default='tech', max_length=5),
        ),
    ]
