# Generated by Django 2.1.2 on 2018-11-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('tickets', '0002_ticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='refered_obj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='objects.Object'),
            preserve_default=False,
        ),
    ]
