# Generated by Django 2.1.2 on 2018-11-01 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_ticket_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assignees',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
