# Generated by Django 2.1.2 on 2018-11-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20181101_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='refered_obj',
            new_name='referred_obj',
        ),
    ]
