# Generated by Django 2.1.2 on 2018-11-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20181101_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='referred_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='objects.Object'),
        ),
    ]
