# Generated by Django 2.1.3 on 2018-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20181102_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reporter',
            field=models.CharField(default='Kalle Kula', max_length=70),
            preserve_default=False,
        ),
    ]
