# Generated by Django 2.1.3 on 2018-11-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20181103_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='internal_id',
            field=models.IntegerField(editable=False),
        ),
    ]
