# Generated by Django 2.1.3 on 2019-03-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0015_auto_20181103_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
