# Generated by Django 2.1.2 on 2018-10-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customers',
            field=models.ManyToManyField(related_name='companies', to='customers.Customer'),
        ),
    ]
