# Generated by Django 2.1.2 on 2018-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='customers',
            field=models.ManyToManyField(blank=True, to='customers.Customer'),
        ),
    ]
