# Generated by Django 2.1.2 on 2018-11-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('companies', '0005_company_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service_objects',
            field=models.ManyToManyField(blank=True, to='objects.Object'),
        ),
    ]
