# Generated by Django 2.1.3 on 2018-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_service_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='company', to='tickets.Ticket'),
        ),
    ]
